import {Router} from 'express';
import userAvatarController, { loginUserController, logoutController, registerUserController, removeImageFromCloudinary, verifyEmailController } from '../controllers/user.controller.js';
import auth from '../middlewares/Auth.js';
import upload from '../middlewares/multer.js';
const userRouter=Router();
userRouter.post('/register',registerUserController);
userRouter.post('/verifyEmail',verifyEmailController);
userRouter.post('/login',loginUserController);
userRouter.get('/logout',auth,logoutController);
userRouter.put('/user-avatar',auth,upload.array('avatar'),userAvatarController);
userRouter.delete('/deleteImage',auth,removeImageFromCloudinary);
export default userRouter;